spring:
  application:
    name: test-config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
server:
<<<<<<< HEAD
  port: 8088
  
#将/actuator/refresh 这个 Endpoint 暴露出来  
management:
  endpoints:
    web:
      exposure:
        include: refres
=======
  port: 8088
>>>>>>> 0008985a7ccb12a3e38b585cc12b7b5bd5bcded0
